// gfx — M4 8bpp indexed render core. No PicOS headers: the app hands us a
// raw RGB565 big-endian framebuffer and asset blobs loaded from SD.
//
// Pipeline: assets stay 8bpp palette-indexed in PSRAM (tiles, sprites); every
// blit expands through the 256-entry CLUT straight into the framebuffer.
// The camera is world-fixed (no rotation), so ground rendering is a direct
// axis-aligned tile blit of the baked tilemap — no sampling pass.
#pragma once

#include <stdint.h>

#define GFX_TILE 16
#define GFX_TRANSPARENT 255
#define GFX_TILEMAP_LAYERS 4   // base + 2 wang layers + road overlay per cell

typedef struct {
    const uint16_t *clut;                 // 256 RGB565 values (panel order)
    const uint8_t *gtile[256];            // global tile idx -> 16x16 8bpp data
} gfx_t;

// Build the global tile pointer table. sections[i] holds counts[i] 16x16
// 8bpp tiles whose global indices start at bases[i] (see tiles_sections.h,
// generated by trackbake from atlas.json).
void gfx_init(gfx_t *g, const uint16_t *clut,
              const uint8_t **sections, const int *bases, const int *counts,
              int n_sections);

// Framebuffer is always 320 wide in this game; h passed for viewport/HUD use.
#define GFX_FB_W 320

void gfx_blit_tile(gfx_t *g, uint16_t *fb, int fb_h,
                   int gidx, int sx, int sy);            // opaque, clipped
void gfx_blit_tile_masked(gfx_t *g, uint16_t *fb, int fb_h,
                          int gidx, int sx, int sy);    // skips 255, clipped
void gfx_blit_sprite(gfx_t *g, uint16_t *fb, int fb_h,
                     const uint8_t *spr, int w, int h,
                     int sx, int sy);                    // masked, clipped
void gfx_fill(gfx_t *g, uint16_t *fb, int fb_h,
              int x, int y, int w, int h, uint8_t pal);
void gfx_text(gfx_t *g, uint16_t *fb, int fb_h,
              int x, int y, const char *s, uint8_t pal); // 6x8, palette colour
void gfx_text_scale(gfx_t *g, uint16_t *fb, int fb_h,
                    int x, int y, const char *s, uint8_t pal, int scale);
int gfx_text_width(const char *s);
