#!/usr/bin/env python3
"""Defines what a PicOS Rally app bundle contains.

Single source of truth, shared by two consumers:
  - .github/workflows/release.yml, which packages the published zip
  - tools/rally_hw.py, which pushes the same set to hardware

The bundle mirrors the on-device app dir that app/main.c expects: assets/
for art (app/main.c:116), tuning/handling.toml (app/main.c:180), and
stage01.bin at the root (app/main.c:196).
"""
import argparse
import hashlib
import io
import json
import os
import re
import sys
import zipfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# app/main.c:145 loads clut.bin with an exact-size check. load_bin() at
# app/main.c:122 refuses a size mismatch, which kills the game at startup.
CLUT_BYTES = 512

# Fixed DOS timestamp (the zip epoch) so identical inputs give an identical
# archive. Without this, mtimes leak in and every build differs.
ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)

# Root-relative bundle members that are not assets.
BASE_FILES = ("main.elf", "app.json", "stage01.bin", "tuning/handling.toml")

# Non-tile assets loaded by load_assets() (app/main.c:145 and :156).
SPRITE_ASSETS = ("clut.bin", "car.bin", "props.bin", "hero.bin")


class BundleError(Exception):
    """Raised when the source tree cannot produce a valid bundle."""


def tile_section_names(root):
    """Read TILE_SEC_NAMES out of core/tiles_sections.h.

    That header is generated by trackbake.py from assets/atlas.json, so
    parsing it means a future stage with a different terrain chain updates
    the bundle automatically rather than silently shipping the wrong tiles.
    """
    path = os.path.join(root, "core", "tiles_sections.h")
    try:
        with open(path, "r", encoding="utf-8") as f:
            src = f.read()
    except OSError as e:
        raise BundleError(f"cannot read {path}: {e}")
    m = re.search(r"TILE_SEC_NAMES\[[^\]]*\]\s*=\s*\{(.*?)\}", src, re.S)
    if not m:
        raise BundleError(f"TILE_SEC_NAMES not found in {path}")
    names = re.findall(r'"([^"]+)"', m.group(1))
    if not names:
        raise BundleError(f"TILE_SEC_NAMES is empty in {path}")
    return names


def bundle_files(root):
    """Return [(absolute_source_path, arcname)], sorted by arcname.

    Paths are resolved from `root` explicitly. Nothing is globbed and
    nothing is discovered by walking, so sdk/native/main.elf can never be
    picked up in place of the real one.
    """
    rels = list(BASE_FILES)
    rels += [f"assets/{n}" for n in SPRITE_ASSETS]
    rels += [f"assets/tiles_{n}.bin" for n in tile_section_names(root)]
    return sorted(((os.path.join(root, r), r) for r in rels),
                  key=lambda pair: pair[1])


def _sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _manifest_hashes(root):
    """Map asset filename to its expected sha256, from assets/manifest.json."""
    path = os.path.join(root, "assets", "manifest.json")
    try:
        with open(path, "r", encoding="utf-8") as f:
            manifest = json.load(f)
    except OSError as e:
        raise BundleError(f"cannot read {path}: {e}")
    except json.JSONDecodeError as e:
        raise BundleError(f"{path} is not valid JSON: {e}")
    out = {}
    for entry in manifest.values():
        if isinstance(entry, dict) and "bin" in entry and "bin_sha256" in entry:
            out[entry["bin"]] = entry["bin_sha256"]
    return out


def verify(root, files):
    """Fail closed on anything that would break the app at load time."""
    for src, arc in files:
        if not os.path.isfile(src):
            raise BundleError(f"missing bundle file: {arc}")

    hashes = _manifest_hashes(root)
    for src, arc in files:
        if not arc.startswith("assets/"):
            continue
        name = os.path.basename(arc)
        # clut.bin has no manifest entry (palettize.py does not record one),
        # so its exact length is the only check available.
        if name == "clut.bin":
            size = os.path.getsize(src)
            if size != CLUT_BYTES:
                raise BundleError(
                    f"clut.bin is {size} bytes, expected {CLUT_BYTES}; "
                    "app/main.c:145 rejects a size mismatch")
            continue
        expected = hashes.get(name)
        if expected is None:
            raise BundleError(
                f"{arc} has no bin_sha256 entry in assets/manifest.json")
        actual = _sha256(src)
        if actual != expected:
            raise BundleError(
                f"{arc} sha256 {actual} does not match manifest {expected}")


def check_version(root, expected):
    """Assert app.json's version equals `expected` (the tag minus its v)."""
    path = os.path.join(root, "app.json")
    try:
        with open(path, "r", encoding="utf-8") as f:
            app = json.load(f)
    except OSError as e:
        raise BundleError(f"cannot read {path}: {e}")
    except json.JSONDecodeError as e:
        raise BundleError(f"{path} is not valid JSON: {e}")
    actual = app.get("version")
    if actual != expected:
        raise BundleError(
            f"app.json version is {actual!r} but the tag expects {expected!r}; "
            "bump app.json and commit before tagging")


def collect(root=REPO_ROOT):
    """Verified bundle contents. Raises BundleError if the tree is unfit."""
    files = bundle_files(root)
    verify(root, files)
    return files


def build_zip_bytes(root=REPO_ROOT, files=None):
    """Deterministic zip: verified contents, sorted, fixed timestamps."""
    if files is None:
        files = collect(root)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for src, arc in files:
            info = zipfile.ZipInfo(arc, date_time=ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            # ZIP spec traditionally encodes on Unix (3) or Windows (0). Setting
            # create_system = 0 fixes the host OS leak so identical inputs produce
            # a byte-identical archive regardless of the build machine.
            info.create_system = 0
            info.external_attr = 0o644 << 16
            with open(src, "rb") as f:
                z.writestr(info, f.read())
    return buf.getvalue()


def main(argv=None):
    p = argparse.ArgumentParser(
        description="Package a PicOS Rally app bundle.")
    p.add_argument("--out", required=True, help="output zip path")
    p.add_argument("--expect-version",
                   help="fail unless app.json's version equals this")
    p.add_argument("--app-dir", default=REPO_ROOT,
                   help="source tree to bundle (default: repo root)")
    args = p.parse_args(argv)

    try:
        if args.expect_version:
            check_version(args.app_dir, args.expect_version)
        files = collect(args.app_dir)
        data = build_zip_bytes(args.app_dir, files=files)
    except BundleError as e:
        print(f"bundle: {e}", file=sys.stderr)
        return 1

    out_dir = os.path.dirname(os.path.abspath(args.out))
    os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "wb") as f:
        f.write(data)
    print(f"bundle: {args.out} ({len(data)} bytes, {len(files)} files)")
    for _, arc in files:
        print(f"  {arc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
