#!/usr/bin/env python3
"""Defines what a PicOS Rally app bundle contains.

Single source of truth, shared by two consumers:
  - .github/workflows/release.yml, which packages the published zip
  - tools/rally_hw.py, which pushes the same set to hardware

The bundle mirrors the on-device app dir that app/main.c expects: assets/
for art (app/main.c:116), tuning/handling.toml (app/main.c:180), and
stage01.bin at the root (app/main.c:196).
"""
import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Root-relative bundle members that are not assets.
BASE_FILES = ("main.elf", "app.json", "stage01.bin", "tuning/handling.toml")

# Non-tile assets loaded by load_assets() (app/main.c:145 and :156).
SPRITE_ASSETS = ("clut.bin", "car.bin", "props.bin", "hero.bin")


class BundleError(Exception):
    """Raised when the source tree cannot produce a valid bundle."""


def tile_section_names(root):
    """Read TILE_SEC_NAMES out of core/tiles_sections.h.

    That header is generated by trackbake.py from assets/atlas.json, so
    parsing it means a future stage with a different terrain chain updates
    the bundle automatically rather than silently shipping the wrong tiles.
    """
    path = os.path.join(root, "core", "tiles_sections.h")
    try:
        with open(path, "r", encoding="utf-8") as f:
            src = f.read()
    except OSError as e:
        raise BundleError(f"cannot read {path}: {e}")
    m = re.search(r"TILE_SEC_NAMES\[[^\]]*\]\s*=\s*\{(.*?)\}", src, re.S)
    if not m:
        raise BundleError(f"TILE_SEC_NAMES not found in {path}")
    names = re.findall(r'"([^"]+)"', m.group(1))
    if not names:
        raise BundleError(f"TILE_SEC_NAMES is empty in {path}")
    return names


def bundle_files(root):
    """Return [(absolute_source_path, arcname)], sorted by arcname.

    Paths are resolved from `root` explicitly. Nothing is globbed and
    nothing is discovered by walking, so sdk/native/main.elf can never be
    picked up in place of the real one.
    """
    rels = list(BASE_FILES)
    rels += [f"assets/{n}" for n in SPRITE_ASSETS]
    rels += [f"assets/tiles_{n}.bin" for n in tile_section_names(root)]
    return sorted(((os.path.join(root, r), r) for r in rels),
                  key=lambda pair: pair[1])
